<?php

function doug_fir_marine() { 

  $styles = array(
    'Default' => array(
      'title' => 'Default',
      'bg' => 'marine_bg-tn.jpg',
    ),
    'seascape' => array(
      'title' => 'Seascape',
      'bg'    => 'marine_bg_1-tn.png',
    ),
    'icons' => array(
      'title'    => 'Icons',
      'bg'       => 'marine_bg_2-tn.png',
    ),
    'waves' => array(
      'title'    => 'Waves',
      'bg'       => 'marine_bg_3-tn.png',
    ),
    'space' => array(
      'title'    => 'Space',
      'bg'       => 'space_bg.jpg',
    ),
  );
  return $styles;
}